
package com.rnr.example.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://webservice.example.rnr.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sqrt", targetNamespace = "http://webservice.example.rnr.com/", className = "com.rnr.example.webservice.Sqrt")
    @ResponseWrapper(localName = "sqrtResponse", targetNamespace = "http://webservice.example.rnr.com/", className = "com.rnr.example.webservice.SqrtResponse")
    @Action(input = "http://webservice.example.rnr.com/Calculator/sqrtRequest", output = "http://webservice.example.rnr.com/Calculator/sqrtResponse")
    public double sqrt(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
